# Federation limits
MAX_FEDERATION_NAME_LENGTH = 60
MAX_FEDERATIONS_PER_USER = 1  # Unless owner
MAX_SUBSCRIPTIONS_PER_FEDERATION = 10
MAX_ADMINS_PER_FEDERATION = 50

# Operation timeouts
FEDERATION_BAN_TIMEOUT = 30  # seconds
IMPORT_EXPORT_RATE_LIMIT = 600  # seconds

# File size limits
MAX_IMPORT_FILE_SIZE_JSON = 1_000_000  # 1MB
MAX_IMPORT_FILE_SIZE_CSV = 50_000_000  # 50MB
