files:
  - source: sophie_bot/localization/en.yaml
    translation: /**/sophie_bot/localization/%locale_with_underscore%.yaml
  - source: /locales/*.pot
    translation: /**/locales/%locale_with_underscore%/%file_name%.po
