from typing import Final

TELEGRAM_MESSAGE_LENGTH_LIMIT: Final[int] = 4096

TELEGRAM_CALLBACK_DATA_MAX_LENGTH: Final[int] = 64

TELEGRAM_ANONYMOUS_ADMIN_BOT_ID: Final[int] = 1087968824

CACHE_DEFAULT_TTL_SECONDS: Final[int] = 1800  # 30 minutes

CACHE_ADMIN_TTL_SECONDS: Final[int] = 7200  # 2 hours

CACHE_FILE_ID_TTL_SECONDS: Final[int] = 2678400  # 31 days

CACHE_MEDIA_TTL_SECONDS: Final[int] = CACHE_FILE_ID_TTL_SECONDS
